# Generated by Django 5.0.6 on 2024-06-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0002_rename_first_name_passenger_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='address',
            new_name='city',
        ),
    ]
