# Generated by Django 5.0.6 on 2024-06-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0003_rename_address_passenger_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='nationally',
            new_name='nationality',
        ),
    ]
