# Generated by Django 5.0.6 on 2024-06-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0004_rename_nationally_passenger_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(choices=[('single', 'Single Journey'), ('return', 'Return Journey')], max_length=10)),
                ('departure_station', models.CharField(max_length=100)),
                ('arrival_station', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('travel_class', models.CharField(choices=[('first_class', 'First Class'), ('second_class', 'Second Class'), ('third_class', 'Third Class'), ('sleeper_class', 'Sleeper Class')], max_length=20)),
                ('number_of_passengers', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('bedroll', models.CharField(choices=[('standard', 'Standard Bed Roll'), ('deluxe', 'Deluxe Bed Roll'), ('premium', 'Premium Bed Roll')], max_length=20)),
                ('number_of_bedrolls', models.PositiveIntegerField()),
            ],
        ),
    ]
