# Generated by Django 5.0.6 on 2024-06-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0006_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
