# Generated by Django 5.0.6 on 2024-06-29 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0011_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.bed'),
        ),
    ]
